spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/devtracker
    username: postgres
    password: chedi123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jpa.repositories.bootstrap-mode: default

server:
  port: 8080

jwt:
  secret: devtracker-super-secret-key-2025-change-in-prod-32chars-minimum
  expiration: 86400000
  refresh-expiration: 604800000


